// @generated by protobuf-ts 2.11.0 with parameter client_generic
// @generated from protobuf file "av_scanner.proto" (package "avscanner", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * ScanRequest represents a request to start a scan
 *
 * @generated from protobuf message avscanner.ScanRequest
 */
export interface ScanRequest {
    /**
     * @generated from protobuf field: string scan_id = 1
     */
    scanId: string; // Unique identifier for the scan
    /**
     * @generated from protobuf field: string scan_path = 2
     */
    scanPath: string; // Path to scan
    /**
     * @generated from protobuf field: string av_tool_name = 3
     */
    avToolName: string; // Name of the AV tool to use (e.g., "clamav")
    /**
     * @generated from protobuf field: string command = 4
     */
    command: string; // Command to execute
}
/**
 * ScanLog represents a single log entry from the scan
 *
 * @generated from protobuf message avscanner.ScanLog
 */
export interface ScanLog {
    /**
     * @generated from protobuf field: string scan_id = 1
     */
    scanId: string; // Scan ID this log belongs to
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string; // Log content
    /**
     * @generated from protobuf field: string timestamp = 3
     */
    timestamp: string; // Timestamp of the log
    /**
     * @generated from protobuf field: avscanner.LogLevel level = 4
     */
    level: LogLevel; // Log level
    /**
     * @generated from protobuf field: string file_path = 5
     */
    filePath: string; // File path being scanned (if applicable)
    /**
     * @generated from protobuf field: int32 progress = 6
     */
    progress: number; // Scan progress (0-100)
}
/**
 * AVCheckRequest represents a request to check AV installation
 *
 * @generated from protobuf message avscanner.AVCheckRequest
 */
export interface AVCheckRequest {
    /**
     * @generated from protobuf field: string av_tool_name = 1
     */
    avToolName: string; // Name of the AV tool to check
    /**
     * @generated from protobuf field: string check_command = 2
     */
    checkCommand: string; // Command to check installation
}
/**
 * AVCheckResponse represents the response to an AV check
 *
 * @generated from protobuf message avscanner.AVCheckResponse
 */
export interface AVCheckResponse {
    /**
     * @generated from protobuf field: bool is_installed = 1
     */
    isInstalled: boolean; // Whether the AV tool is installed
    /**
     * @generated from protobuf field: string version = 2
     */
    version: string; // Version of the AV tool
    /**
     * @generated from protobuf field: string error_message = 3
     */
    errorMessage: string; // Error message if any
}
/**
 * AVInfoRequest represents a request for AV information
 *
 * @generated from protobuf message avscanner.AVInfoRequest
 */
export interface AVInfoRequest {
    /**
     * @generated from protobuf field: string av_tool_name = 1
     */
    avToolName: string; // Name of the AV tool
    /**
     * @generated from protobuf field: string info_command = 2
     */
    infoCommand: string; // Command to get info
}
/**
 * AVInfoResponse represents AV tool information
 *
 * @generated from protobuf message avscanner.AVInfoResponse
 */
export interface AVInfoResponse {
    /**
     * @generated from protobuf field: string version = 1
     */
    version: string; // Version of the AV tool
    /**
     * @generated from protobuf field: string signature_version = 2
     */
    signatureVersion: string; // Version of signature database
    /**
     * @generated from protobuf field: string last_update = 3
     */
    lastUpdate: string; // Last update time
    /**
     * @generated from protobuf field: string error_message = 4
     */
    errorMessage: string; // Error message if any
}
/**
 * HealthCheckRequest represents a request to check server health
 *
 * @generated from protobuf message avscanner.HealthCheckRequest
 */
export interface HealthCheckRequest {
    /**
     * @generated from protobuf field: string check_command = 1
     */
    checkCommand: string; // Command to check health
}
/**
 * HealthCheckResponse represents server health status
 *
 * @generated from protobuf message avscanner.HealthCheckResponse
 */
export interface HealthCheckResponse {
    /**
     * @generated from protobuf field: bool is_healthy = 1
     */
    isHealthy: boolean; // Whether the server is healthy
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string; // Status message
    /**
     * @generated from protobuf field: repeated string issues = 3
     */
    issues: string[]; // List of issues if any
    /**
     * @generated from protobuf field: string last_check = 4
     */
    lastCheck: string; // Last check timestamp
}
/**
 * ResourceResponse represents system resource usage
 *
 * @generated from protobuf message avscanner.ResourceResponse
 */
export interface ResourceResponse {
    /**
     * @generated from protobuf field: double cpu_usage = 1
     */
    cpuUsage: number; // CPU usage percentage
    /**
     * @generated from protobuf field: double memory_usage = 2
     */
    memoryUsage: number; // Memory usage percentage
    /**
     * @generated from protobuf field: double disk_usage = 3
     */
    diskUsage: number; // Disk usage percentage
    /**
     * @generated from protobuf field: int32 active_scans = 4
     */
    activeScans: number; // Number of active scans
    /**
     * @generated from protobuf field: string last_update = 5
     */
    lastUpdate: string; // Last update timestamp
}
/**
 * StreamResourceRequest represents a request for streaming resource usage
 *
 * @generated from protobuf message avscanner.StreamResourceRequest
 */
export interface StreamResourceRequest {
    /**
     * @generated from protobuf field: int32 interval_seconds = 1
     */
    intervalSeconds: number; // Interval between updates in seconds
    /**
     * @generated from protobuf field: int32 duration_seconds = 2
     */
    durationSeconds: number; // Duration to stream for (0 for indefinite)
}
/**
 * LogLevel represents the severity level of a log message
 *
 * @generated from protobuf enum avscanner.LogLevel
 */
export enum LogLevel {
    /**
     * @generated from protobuf enum value: INFO = 0;
     */
    INFO = 0,
    /**
     * @generated from protobuf enum value: WARNING = 1;
     */
    WARNING = 1,
    /**
     * @generated from protobuf enum value: ERROR = 2;
     */
    ERROR = 2,
    /**
     * @generated from protobuf enum value: DEBUG = 3;
     */
    DEBUG = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ScanRequest$Type extends MessageType<ScanRequest> {
    constructor() {
        super("avscanner.ScanRequest", [
            { no: 1, name: "scan_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "scan_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "av_tool_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "command", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScanRequest>): ScanRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scanId = "";
        message.scanPath = "";
        message.avToolName = "";
        message.command = "";
        if (value !== undefined)
            reflectionMergePartial<ScanRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanRequest): ScanRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string scan_id */ 1:
                    message.scanId = reader.string();
                    break;
                case /* string scan_path */ 2:
                    message.scanPath = reader.string();
                    break;
                case /* string av_tool_name */ 3:
                    message.avToolName = reader.string();
                    break;
                case /* string command */ 4:
                    message.command = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string scan_id = 1; */
        if (message.scanId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.scanId);
        /* string scan_path = 2; */
        if (message.scanPath !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.scanPath);
        /* string av_tool_name = 3; */
        if (message.avToolName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.avToolName);
        /* string command = 4; */
        if (message.command !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.command);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.ScanRequest
 */
export const ScanRequest = new ScanRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanLog$Type extends MessageType<ScanLog> {
    constructor() {
        super("avscanner.ScanLog", [
            { no: 1, name: "scan_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "level", kind: "enum", T: () => ["avscanner.LogLevel", LogLevel] },
            { no: 5, name: "file_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "progress", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ScanLog>): ScanLog {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scanId = "";
        message.content = "";
        message.timestamp = "";
        message.level = 0;
        message.filePath = "";
        message.progress = 0;
        if (value !== undefined)
            reflectionMergePartial<ScanLog>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanLog): ScanLog {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string scan_id */ 1:
                    message.scanId = reader.string();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                case /* string timestamp */ 3:
                    message.timestamp = reader.string();
                    break;
                case /* avscanner.LogLevel level */ 4:
                    message.level = reader.int32();
                    break;
                case /* string file_path */ 5:
                    message.filePath = reader.string();
                    break;
                case /* int32 progress */ 6:
                    message.progress = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanLog, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string scan_id = 1; */
        if (message.scanId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.scanId);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        /* string timestamp = 3; */
        if (message.timestamp !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.timestamp);
        /* avscanner.LogLevel level = 4; */
        if (message.level !== 0)
            writer.tag(4, WireType.Varint).int32(message.level);
        /* string file_path = 5; */
        if (message.filePath !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.filePath);
        /* int32 progress = 6; */
        if (message.progress !== 0)
            writer.tag(6, WireType.Varint).int32(message.progress);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.ScanLog
 */
export const ScanLog = new ScanLog$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AVCheckRequest$Type extends MessageType<AVCheckRequest> {
    constructor() {
        super("avscanner.AVCheckRequest", [
            { no: 1, name: "av_tool_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "check_command", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AVCheckRequest>): AVCheckRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.avToolName = "";
        message.checkCommand = "";
        if (value !== undefined)
            reflectionMergePartial<AVCheckRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AVCheckRequest): AVCheckRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string av_tool_name */ 1:
                    message.avToolName = reader.string();
                    break;
                case /* string check_command */ 2:
                    message.checkCommand = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AVCheckRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string av_tool_name = 1; */
        if (message.avToolName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.avToolName);
        /* string check_command = 2; */
        if (message.checkCommand !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.checkCommand);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.AVCheckRequest
 */
export const AVCheckRequest = new AVCheckRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AVCheckResponse$Type extends MessageType<AVCheckResponse> {
    constructor() {
        super("avscanner.AVCheckResponse", [
            { no: 1, name: "is_installed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "error_message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AVCheckResponse>): AVCheckResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isInstalled = false;
        message.version = "";
        message.errorMessage = "";
        if (value !== undefined)
            reflectionMergePartial<AVCheckResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AVCheckResponse): AVCheckResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_installed */ 1:
                    message.isInstalled = reader.bool();
                    break;
                case /* string version */ 2:
                    message.version = reader.string();
                    break;
                case /* string error_message */ 3:
                    message.errorMessage = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AVCheckResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_installed = 1; */
        if (message.isInstalled !== false)
            writer.tag(1, WireType.Varint).bool(message.isInstalled);
        /* string version = 2; */
        if (message.version !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.version);
        /* string error_message = 3; */
        if (message.errorMessage !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.errorMessage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.AVCheckResponse
 */
export const AVCheckResponse = new AVCheckResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AVInfoRequest$Type extends MessageType<AVInfoRequest> {
    constructor() {
        super("avscanner.AVInfoRequest", [
            { no: 1, name: "av_tool_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "info_command", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AVInfoRequest>): AVInfoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.avToolName = "";
        message.infoCommand = "";
        if (value !== undefined)
            reflectionMergePartial<AVInfoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AVInfoRequest): AVInfoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string av_tool_name */ 1:
                    message.avToolName = reader.string();
                    break;
                case /* string info_command */ 2:
                    message.infoCommand = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AVInfoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string av_tool_name = 1; */
        if (message.avToolName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.avToolName);
        /* string info_command = 2; */
        if (message.infoCommand !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.infoCommand);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.AVInfoRequest
 */
export const AVInfoRequest = new AVInfoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AVInfoResponse$Type extends MessageType<AVInfoResponse> {
    constructor() {
        super("avscanner.AVInfoResponse", [
            { no: 1, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "signature_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "last_update", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "error_message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AVInfoResponse>): AVInfoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.version = "";
        message.signatureVersion = "";
        message.lastUpdate = "";
        message.errorMessage = "";
        if (value !== undefined)
            reflectionMergePartial<AVInfoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AVInfoResponse): AVInfoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string version */ 1:
                    message.version = reader.string();
                    break;
                case /* string signature_version */ 2:
                    message.signatureVersion = reader.string();
                    break;
                case /* string last_update */ 3:
                    message.lastUpdate = reader.string();
                    break;
                case /* string error_message */ 4:
                    message.errorMessage = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AVInfoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string version = 1; */
        if (message.version !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.version);
        /* string signature_version = 2; */
        if (message.signatureVersion !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.signatureVersion);
        /* string last_update = 3; */
        if (message.lastUpdate !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.lastUpdate);
        /* string error_message = 4; */
        if (message.errorMessage !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.errorMessage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.AVInfoResponse
 */
export const AVInfoResponse = new AVInfoResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealthCheckRequest$Type extends MessageType<HealthCheckRequest> {
    constructor() {
        super("avscanner.HealthCheckRequest", [
            { no: 1, name: "check_command", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HealthCheckRequest>): HealthCheckRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.checkCommand = "";
        if (value !== undefined)
            reflectionMergePartial<HealthCheckRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealthCheckRequest): HealthCheckRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string check_command */ 1:
                    message.checkCommand = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HealthCheckRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string check_command = 1; */
        if (message.checkCommand !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.checkCommand);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.HealthCheckRequest
 */
export const HealthCheckRequest = new HealthCheckRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealthCheckResponse$Type extends MessageType<HealthCheckResponse> {
    constructor() {
        super("avscanner.HealthCheckResponse", [
            { no: 1, name: "is_healthy", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "issues", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "last_check", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HealthCheckResponse>): HealthCheckResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isHealthy = false;
        message.status = "";
        message.issues = [];
        message.lastCheck = "";
        if (value !== undefined)
            reflectionMergePartial<HealthCheckResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealthCheckResponse): HealthCheckResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_healthy */ 1:
                    message.isHealthy = reader.bool();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* repeated string issues */ 3:
                    message.issues.push(reader.string());
                    break;
                case /* string last_check */ 4:
                    message.lastCheck = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HealthCheckResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_healthy = 1; */
        if (message.isHealthy !== false)
            writer.tag(1, WireType.Varint).bool(message.isHealthy);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* repeated string issues = 3; */
        for (let i = 0; i < message.issues.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.issues[i]);
        /* string last_check = 4; */
        if (message.lastCheck !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.lastCheck);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.HealthCheckResponse
 */
export const HealthCheckResponse = new HealthCheckResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResourceResponse$Type extends MessageType<ResourceResponse> {
    constructor() {
        super("avscanner.ResourceResponse", [
            { no: 1, name: "cpu_usage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "memory_usage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "disk_usage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "active_scans", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "last_update", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ResourceResponse>): ResourceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cpuUsage = 0;
        message.memoryUsage = 0;
        message.diskUsage = 0;
        message.activeScans = 0;
        message.lastUpdate = "";
        if (value !== undefined)
            reflectionMergePartial<ResourceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ResourceResponse): ResourceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double cpu_usage */ 1:
                    message.cpuUsage = reader.double();
                    break;
                case /* double memory_usage */ 2:
                    message.memoryUsage = reader.double();
                    break;
                case /* double disk_usage */ 3:
                    message.diskUsage = reader.double();
                    break;
                case /* int32 active_scans */ 4:
                    message.activeScans = reader.int32();
                    break;
                case /* string last_update */ 5:
                    message.lastUpdate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ResourceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double cpu_usage = 1; */
        if (message.cpuUsage !== 0)
            writer.tag(1, WireType.Bit64).double(message.cpuUsage);
        /* double memory_usage = 2; */
        if (message.memoryUsage !== 0)
            writer.tag(2, WireType.Bit64).double(message.memoryUsage);
        /* double disk_usage = 3; */
        if (message.diskUsage !== 0)
            writer.tag(3, WireType.Bit64).double(message.diskUsage);
        /* int32 active_scans = 4; */
        if (message.activeScans !== 0)
            writer.tag(4, WireType.Varint).int32(message.activeScans);
        /* string last_update = 5; */
        if (message.lastUpdate !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.lastUpdate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.ResourceResponse
 */
export const ResourceResponse = new ResourceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamResourceRequest$Type extends MessageType<StreamResourceRequest> {
    constructor() {
        super("avscanner.StreamResourceRequest", [
            { no: 1, name: "interval_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "duration_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<StreamResourceRequest>): StreamResourceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.intervalSeconds = 0;
        message.durationSeconds = 0;
        if (value !== undefined)
            reflectionMergePartial<StreamResourceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamResourceRequest): StreamResourceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 interval_seconds */ 1:
                    message.intervalSeconds = reader.int32();
                    break;
                case /* int32 duration_seconds */ 2:
                    message.durationSeconds = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamResourceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 interval_seconds = 1; */
        if (message.intervalSeconds !== 0)
            writer.tag(1, WireType.Varint).int32(message.intervalSeconds);
        /* int32 duration_seconds = 2; */
        if (message.durationSeconds !== 0)
            writer.tag(2, WireType.Varint).int32(message.durationSeconds);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message avscanner.StreamResourceRequest
 */
export const StreamResourceRequest = new StreamResourceRequest$Type();
/**
 * @generated ServiceType for protobuf service avscanner.AVScanner
 */
export const AVScanner = new ServiceType("avscanner.AVScanner", [
    { name: "StartScan", serverStreaming: true, options: {}, I: ScanRequest, O: ScanLog }
]);
/**
 * @generated ServiceType for protobuf service avscanner.AVStatus
 */
export const AVStatus = new ServiceType("avscanner.AVStatus", [
    { name: "CheckAVInstalled", options: {}, I: AVCheckRequest, O: AVCheckResponse },
    { name: "GetAVInfo", options: {}, I: AVInfoRequest, O: AVInfoResponse }
]);
/**
 * @generated ServiceType for protobuf service avscanner.VMMonitor
 */
export const VMMonitor = new ServiceType("avscanner.VMMonitor", [
    { name: "CheckServerHealth", options: {}, I: HealthCheckRequest, O: HealthCheckResponse },
    { name: "StreamResourceUsage", serverStreaming: true, options: {}, I: StreamResourceRequest, O: ResourceResponse }
]);
