// @generated by protobuf-ts 2.11.0 with parameter client_generic
// @generated from protobuf file "av_scanner.proto" (package "avscanner", syntax proto3)
// tslint:disable
import { VMMonitor } from "./av_scanner";
import type { ResourceResponse } from "./av_scanner";
import type { StreamResourceRequest } from "./av_scanner";
import type { HealthCheckResponse } from "./av_scanner";
import type { HealthCheckRequest } from "./av_scanner";
import { AVStatus } from "./av_scanner";
import type { AVInfoResponse } from "./av_scanner";
import type { AVInfoRequest } from "./av_scanner";
import type { AVCheckResponse } from "./av_scanner";
import type { AVCheckRequest } from "./av_scanner";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AVScanner } from "./av_scanner";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ScanLog } from "./av_scanner";
import type { ScanRequest } from "./av_scanner";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * AVScanner service definition
 *
 * @generated from protobuf service avscanner.AVScanner
 */
export interface IAVScannerClient {
    /**
     * StartScan starts a scan and returns a stream of scan logs
     *
     * @generated from protobuf rpc: StartScan
     */
    startScan(input: ScanRequest, options?: RpcOptions): ServerStreamingCall<ScanRequest, ScanLog>;
}
/**
 * AVScanner service definition
 *
 * @generated from protobuf service avscanner.AVScanner
 */
export class AVScannerClient implements IAVScannerClient, ServiceInfo {
    typeName = AVScanner.typeName;
    methods = AVScanner.methods;
    options = AVScanner.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * StartScan starts a scan and returns a stream of scan logs
     *
     * @generated from protobuf rpc: StartScan
     */
    startScan(input: ScanRequest, options?: RpcOptions): ServerStreamingCall<ScanRequest, ScanLog> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ScanRequest, ScanLog>("serverStreaming", this._transport, method, opt, input);
    }
}
/**
 * AVStatus service definition
 *
 * @generated from protobuf service avscanner.AVStatus
 */
export interface IAVStatusClient {
    /**
     * CheckAVInstalled checks if an AV tool is installed
     *
     * @generated from protobuf rpc: CheckAVInstalled
     */
    checkAVInstalled(input: AVCheckRequest, options?: RpcOptions): UnaryCall<AVCheckRequest, AVCheckResponse>;
    /**
     * GetAVInfo gets version and signature information
     *
     * @generated from protobuf rpc: GetAVInfo
     */
    getAVInfo(input: AVInfoRequest, options?: RpcOptions): UnaryCall<AVInfoRequest, AVInfoResponse>;
}
/**
 * AVStatus service definition
 *
 * @generated from protobuf service avscanner.AVStatus
 */
export class AVStatusClient implements IAVStatusClient, ServiceInfo {
    typeName = AVStatus.typeName;
    methods = AVStatus.methods;
    options = AVStatus.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * CheckAVInstalled checks if an AV tool is installed
     *
     * @generated from protobuf rpc: CheckAVInstalled
     */
    checkAVInstalled(input: AVCheckRequest, options?: RpcOptions): UnaryCall<AVCheckRequest, AVCheckResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AVCheckRequest, AVCheckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetAVInfo gets version and signature information
     *
     * @generated from protobuf rpc: GetAVInfo
     */
    getAVInfo(input: AVInfoRequest, options?: RpcOptions): UnaryCall<AVInfoRequest, AVInfoResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AVInfoRequest, AVInfoResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * VMMonitor service definition
 *
 * @generated from protobuf service avscanner.VMMonitor
 */
export interface IVMMonitorClient {
    /**
     * CheckServerHealth checks the health of the server
     *
     * @generated from protobuf rpc: CheckServerHealth
     */
    checkServerHealth(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse>;
    /**
     * StreamResourceUsage streams real-time system resource usage
     *
     * @generated from protobuf rpc: StreamResourceUsage
     */
    streamResourceUsage(input: StreamResourceRequest, options?: RpcOptions): ServerStreamingCall<StreamResourceRequest, ResourceResponse>;
}
/**
 * VMMonitor service definition
 *
 * @generated from protobuf service avscanner.VMMonitor
 */
export class VMMonitorClient implements IVMMonitorClient, ServiceInfo {
    typeName = VMMonitor.typeName;
    methods = VMMonitor.methods;
    options = VMMonitor.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * CheckServerHealth checks the health of the server
     *
     * @generated from protobuf rpc: CheckServerHealth
     */
    checkServerHealth(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * StreamResourceUsage streams real-time system resource usage
     *
     * @generated from protobuf rpc: StreamResourceUsage
     */
    streamResourceUsage(input: StreamResourceRequest, options?: RpcOptions): ServerStreamingCall<StreamResourceRequest, ResourceResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamResourceRequest, ResourceResponse>("serverStreaming", this._transport, method, opt, input);
    }
}
