// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: av_scanner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AVScanner_StartScan_FullMethodName = "/avscanner.AVScanner/StartScan"
)

// AVScannerClient is the client API for AVScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AVScanner service definition
type AVScannerClient interface {
	// StartScan starts a scan and returns a stream of scan logs
	StartScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanLog], error)
}

type aVScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewAVScannerClient(cc grpc.ClientConnInterface) AVScannerClient {
	return &aVScannerClient{cc}
}

func (c *aVScannerClient) StartScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AVScanner_ServiceDesc.Streams[0], AVScanner_StartScan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AVScanner_StartScanClient = grpc.ServerStreamingClient[ScanLog]

// AVScannerServer is the server API for AVScanner service.
// All implementations must embed UnimplementedAVScannerServer
// for forward compatibility.
//
// AVScanner service definition
type AVScannerServer interface {
	// StartScan starts a scan and returns a stream of scan logs
	StartScan(*ScanRequest, grpc.ServerStreamingServer[ScanLog]) error
	mustEmbedUnimplementedAVScannerServer()
}

// UnimplementedAVScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAVScannerServer struct{}

func (UnimplementedAVScannerServer) StartScan(*ScanRequest, grpc.ServerStreamingServer[ScanLog]) error {
	return status.Errorf(codes.Unimplemented, "method StartScan not implemented")
}
func (UnimplementedAVScannerServer) mustEmbedUnimplementedAVScannerServer() {}
func (UnimplementedAVScannerServer) testEmbeddedByValue()                   {}

// UnsafeAVScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AVScannerServer will
// result in compilation errors.
type UnsafeAVScannerServer interface {
	mustEmbedUnimplementedAVScannerServer()
}

func RegisterAVScannerServer(s grpc.ServiceRegistrar, srv AVScannerServer) {
	// If the following call pancis, it indicates UnimplementedAVScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AVScanner_ServiceDesc, srv)
}

func _AVScanner_StartScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AVScannerServer).StartScan(m, &grpc.GenericServerStream[ScanRequest, ScanLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AVScanner_StartScanServer = grpc.ServerStreamingServer[ScanLog]

// AVScanner_ServiceDesc is the grpc.ServiceDesc for AVScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AVScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avscanner.AVScanner",
	HandlerType: (*AVScannerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartScan",
			Handler:       _AVScanner_StartScan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "av_scanner.proto",
}

const (
	AVStatus_CheckAVInstalled_FullMethodName = "/avscanner.AVStatus/CheckAVInstalled"
	AVStatus_GetAVInfo_FullMethodName        = "/avscanner.AVStatus/GetAVInfo"
)

// AVStatusClient is the client API for AVStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AVStatus service definition
type AVStatusClient interface {
	// CheckAVInstalled checks if an AV tool is installed
	CheckAVInstalled(ctx context.Context, in *AVCheckRequest, opts ...grpc.CallOption) (*AVCheckResponse, error)
	// GetAVInfo gets version and signature information
	GetAVInfo(ctx context.Context, in *AVInfoRequest, opts ...grpc.CallOption) (*AVInfoResponse, error)
}

type aVStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewAVStatusClient(cc grpc.ClientConnInterface) AVStatusClient {
	return &aVStatusClient{cc}
}

func (c *aVStatusClient) CheckAVInstalled(ctx context.Context, in *AVCheckRequest, opts ...grpc.CallOption) (*AVCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AVCheckResponse)
	err := c.cc.Invoke(ctx, AVStatus_CheckAVInstalled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aVStatusClient) GetAVInfo(ctx context.Context, in *AVInfoRequest, opts ...grpc.CallOption) (*AVInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AVInfoResponse)
	err := c.cc.Invoke(ctx, AVStatus_GetAVInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AVStatusServer is the server API for AVStatus service.
// All implementations must embed UnimplementedAVStatusServer
// for forward compatibility.
//
// AVStatus service definition
type AVStatusServer interface {
	// CheckAVInstalled checks if an AV tool is installed
	CheckAVInstalled(context.Context, *AVCheckRequest) (*AVCheckResponse, error)
	// GetAVInfo gets version and signature information
	GetAVInfo(context.Context, *AVInfoRequest) (*AVInfoResponse, error)
	mustEmbedUnimplementedAVStatusServer()
}

// UnimplementedAVStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAVStatusServer struct{}

func (UnimplementedAVStatusServer) CheckAVInstalled(context.Context, *AVCheckRequest) (*AVCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAVInstalled not implemented")
}
func (UnimplementedAVStatusServer) GetAVInfo(context.Context, *AVInfoRequest) (*AVInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAVInfo not implemented")
}
func (UnimplementedAVStatusServer) mustEmbedUnimplementedAVStatusServer() {}
func (UnimplementedAVStatusServer) testEmbeddedByValue()                  {}

// UnsafeAVStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AVStatusServer will
// result in compilation errors.
type UnsafeAVStatusServer interface {
	mustEmbedUnimplementedAVStatusServer()
}

func RegisterAVStatusServer(s grpc.ServiceRegistrar, srv AVStatusServer) {
	// If the following call pancis, it indicates UnimplementedAVStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AVStatus_ServiceDesc, srv)
}

func _AVStatus_CheckAVInstalled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AVCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AVStatusServer).CheckAVInstalled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AVStatus_CheckAVInstalled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AVStatusServer).CheckAVInstalled(ctx, req.(*AVCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AVStatus_GetAVInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AVInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AVStatusServer).GetAVInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AVStatus_GetAVInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AVStatusServer).GetAVInfo(ctx, req.(*AVInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AVStatus_ServiceDesc is the grpc.ServiceDesc for AVStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AVStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avscanner.AVStatus",
	HandlerType: (*AVStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAVInstalled",
			Handler:    _AVStatus_CheckAVInstalled_Handler,
		},
		{
			MethodName: "GetAVInfo",
			Handler:    _AVStatus_GetAVInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "av_scanner.proto",
}

const (
	VMMonitor_CheckServerHealth_FullMethodName   = "/avscanner.VMMonitor/CheckServerHealth"
	VMMonitor_StreamResourceUsage_FullMethodName = "/avscanner.VMMonitor/StreamResourceUsage"
)

// VMMonitorClient is the client API for VMMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VMMonitor service definition
type VMMonitorClient interface {
	// CheckServerHealth checks the health of the server
	CheckServerHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// StreamResourceUsage streams real-time system resource usage
	StreamResourceUsage(ctx context.Context, in *StreamResourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceResponse], error)
}

type vMMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewVMMonitorClient(cc grpc.ClientConnInterface) VMMonitorClient {
	return &vMMonitorClient{cc}
}

func (c *vMMonitorClient) CheckServerHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, VMMonitor_CheckServerHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMonitorClient) StreamResourceUsage(ctx context.Context, in *StreamResourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMMonitor_ServiceDesc.Streams[0], VMMonitor_StreamResourceUsage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamResourceRequest, ResourceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMMonitor_StreamResourceUsageClient = grpc.ServerStreamingClient[ResourceResponse]

// VMMonitorServer is the server API for VMMonitor service.
// All implementations must embed UnimplementedVMMonitorServer
// for forward compatibility.
//
// VMMonitor service definition
type VMMonitorServer interface {
	// CheckServerHealth checks the health of the server
	CheckServerHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// StreamResourceUsage streams real-time system resource usage
	StreamResourceUsage(*StreamResourceRequest, grpc.ServerStreamingServer[ResourceResponse]) error
	mustEmbedUnimplementedVMMonitorServer()
}

// UnimplementedVMMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMMonitorServer struct{}

func (UnimplementedVMMonitorServer) CheckServerHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckServerHealth not implemented")
}
func (UnimplementedVMMonitorServer) StreamResourceUsage(*StreamResourceRequest, grpc.ServerStreamingServer[ResourceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamResourceUsage not implemented")
}
func (UnimplementedVMMonitorServer) mustEmbedUnimplementedVMMonitorServer() {}
func (UnimplementedVMMonitorServer) testEmbeddedByValue()                   {}

// UnsafeVMMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMMonitorServer will
// result in compilation errors.
type UnsafeVMMonitorServer interface {
	mustEmbedUnimplementedVMMonitorServer()
}

func RegisterVMMonitorServer(s grpc.ServiceRegistrar, srv VMMonitorServer) {
	// If the following call pancis, it indicates UnimplementedVMMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMMonitor_ServiceDesc, srv)
}

func _VMMonitor_CheckServerHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMonitorServer).CheckServerHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMonitor_CheckServerHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMonitorServer).CheckServerHealth(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMonitor_StreamResourceUsage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamResourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMMonitorServer).StreamResourceUsage(m, &grpc.GenericServerStream[StreamResourceRequest, ResourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMMonitor_StreamResourceUsageServer = grpc.ServerStreamingServer[ResourceResponse]

// VMMonitor_ServiceDesc is the grpc.ServiceDesc for VMMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avscanner.VMMonitor",
	HandlerType: (*VMMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckServerHealth",
			Handler:    _VMMonitor_CheckServerHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResourceUsage",
			Handler:       _VMMonitor_StreamResourceUsage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "av_scanner.proto",
}
