// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: av_scanner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogLevel represents the severity level of a log message
type LogLevel int32

const (
	LogLevel_INFO    LogLevel = 0
	LogLevel_WARNING LogLevel = 1
	LogLevel_ERROR   LogLevel = 2
	LogLevel_DEBUG   LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "ERROR",
		3: "DEBUG",
	}
	LogLevel_value = map[string]int32{
		"INFO":    0,
		"WARNING": 1,
		"ERROR":   2,
		"DEBUG":   3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_av_scanner_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_av_scanner_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{0}
}

// ScanRequest represents a request to start a scan
type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	ScanPath      string                 `protobuf:"bytes,2,opt,name=scan_path,json=scanPath,proto3" json:"scan_path,omitempty"`
	AvToolName    string                 `protobuf:"bytes,3,opt,name=av_tool_name,json=avToolName,proto3" json:"av_tool_name,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Recursive     bool                   `protobuf:"varint,5,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_av_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanRequest) GetScanPath() string {
	if x != nil {
		return x.ScanPath
	}
	return ""
}

func (x *ScanRequest) GetAvToolName() string {
	if x != nil {
		return x.AvToolName
	}
	return ""
}

func (x *ScanRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ScanRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// ScanLog represents a single log entry from the scan
type ScanLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`          // Scan ID this log belongs to
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // Log content
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Timestamp of the log
	Level         LogLevel               `protobuf:"varint,4,opt,name=level,proto3,enum=avscanner.LogLevel" json:"level,omitempty"` // Log level
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`    // File path being scanned (if applicable)
	Progress      int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`                   // Scan progress (0-100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLog) Reset() {
	*x = ScanLog{}
	mi := &file_av_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLog) ProtoMessage() {}

func (x *ScanLog) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLog.ProtoReflect.Descriptor instead.
func (*ScanLog) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanLog) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScanLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ScanLog) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_INFO
}

func (x *ScanLog) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ScanLog) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// AVCheckRequest represents a request to check AV installation
type AVCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvToolName    string                 `protobuf:"bytes,1,opt,name=av_tool_name,json=avToolName,proto3" json:"av_tool_name,omitempty"`     // Name of the AV tool to check
	CheckCommand  string                 `protobuf:"bytes,2,opt,name=check_command,json=checkCommand,proto3" json:"check_command,omitempty"` // Command to check installation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AVCheckRequest) Reset() {
	*x = AVCheckRequest{}
	mi := &file_av_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AVCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AVCheckRequest) ProtoMessage() {}

func (x *AVCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AVCheckRequest.ProtoReflect.Descriptor instead.
func (*AVCheckRequest) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *AVCheckRequest) GetAvToolName() string {
	if x != nil {
		return x.AvToolName
	}
	return ""
}

func (x *AVCheckRequest) GetCheckCommand() string {
	if x != nil {
		return x.CheckCommand
	}
	return ""
}

// AVCheckResponse represents the response to an AV check
type AVCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInstalled   bool                   `protobuf:"varint,1,opt,name=is_installed,json=isInstalled,proto3" json:"is_installed,omitempty"`   // Whether the AV tool is installed
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                               // Version of the AV tool
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AVCheckResponse) Reset() {
	*x = AVCheckResponse{}
	mi := &file_av_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AVCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AVCheckResponse) ProtoMessage() {}

func (x *AVCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AVCheckResponse.ProtoReflect.Descriptor instead.
func (*AVCheckResponse) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *AVCheckResponse) GetIsInstalled() bool {
	if x != nil {
		return x.IsInstalled
	}
	return false
}

func (x *AVCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AVCheckResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// AVInfoRequest represents a request for AV information
type AVInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvToolName    string                 `protobuf:"bytes,1,opt,name=av_tool_name,json=avToolName,proto3" json:"av_tool_name,omitempty"`  // Name of the AV tool
	InfoCommand   string                 `protobuf:"bytes,2,opt,name=info_command,json=infoCommand,proto3" json:"info_command,omitempty"` // Command to get info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AVInfoRequest) Reset() {
	*x = AVInfoRequest{}
	mi := &file_av_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AVInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AVInfoRequest) ProtoMessage() {}

func (x *AVInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AVInfoRequest.ProtoReflect.Descriptor instead.
func (*AVInfoRequest) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *AVInfoRequest) GetAvToolName() string {
	if x != nil {
		return x.AvToolName
	}
	return ""
}

func (x *AVInfoRequest) GetInfoCommand() string {
	if x != nil {
		return x.InfoCommand
	}
	return ""
}

// AVInfoResponse represents AV tool information
type AVInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                           // Version of the AV tool
	SignatureVersion string                 `protobuf:"bytes,2,opt,name=signature_version,json=signatureVersion,proto3" json:"signature_version,omitempty"` // Version of signature database
	LastUpdate       string                 `protobuf:"bytes,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`                   // Last update time
	ErrorMessage     string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`             // Error message if any
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AVInfoResponse) Reset() {
	*x = AVInfoResponse{}
	mi := &file_av_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AVInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AVInfoResponse) ProtoMessage() {}

func (x *AVInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AVInfoResponse.ProtoReflect.Descriptor instead.
func (*AVInfoResponse) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *AVInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AVInfoResponse) GetSignatureVersion() string {
	if x != nil {
		return x.SignatureVersion
	}
	return ""
}

func (x *AVInfoResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *AVInfoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HealthCheckRequest represents a request to check server health
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckCommand  string                 `protobuf:"bytes,1,opt,name=check_command,json=checkCommand,proto3" json:"check_command,omitempty"` // Command to check health
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_av_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetCheckCommand() string {
	if x != nil {
		return x.CheckCommand
	}
	return ""
}

// HealthCheckResponse represents server health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"` // Whether the server is healthy
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                         // Status message
	Issues        []string               `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`                         // List of issues if any
	LastCheck     string                 `protobuf:"bytes,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`  // Last check timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_av_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *HealthCheckResponse) GetLastCheck() string {
	if x != nil {
		return x.LastCheck
	}
	return ""
}

// ResourceResponse represents system resource usage
type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // CPU usage percentage
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // Memory usage percentage
	DiskUsage     float64                `protobuf:"fixed64,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`       // Disk usage percentage
	ActiveScans   int32                  `protobuf:"varint,4,opt,name=active_scans,json=activeScans,proto3" json:"active_scans,omitempty"`  // Number of active scans
	LastUpdate    string                 `protobuf:"bytes,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`      // Last update timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_av_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ResourceResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ResourceResponse) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *ResourceResponse) GetActiveScans() int32 {
	if x != nil {
		return x.ActiveScans
	}
	return 0
}

func (x *ResourceResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

// StreamResourceRequest represents a request for streaming resource usage
type StreamResourceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // Interval between updates in seconds
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Duration to stream for (0 for indefinite)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamResourceRequest) Reset() {
	*x = StreamResourceRequest{}
	mi := &file_av_scanner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResourceRequest) ProtoMessage() {}

func (x *StreamResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_av_scanner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResourceRequest.ProtoReflect.Descriptor instead.
func (*StreamResourceRequest) Descriptor() ([]byte, []int) {
	return file_av_scanner_proto_rawDescGZIP(), []int{9}
}

func (x *StreamResourceRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *StreamResourceRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

var File_av_scanner_proto protoreflect.FileDescriptor

const file_av_scanner_proto_rawDesc = "" +
	"\n" +
	"\x10av_scanner.proto\x12\tavscanner\"\x9d\x01\n" +
	"\vScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x1b\n" +
	"\tscan_path\x18\x02 \x01(\tR\bscanPath\x12 \n" +
	"\fav_tool_name\x18\x03 \x01(\tR\n" +
	"avToolName\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x1c\n" +
	"\trecursive\x18\x05 \x01(\bR\trecursive\"\xbe\x01\n" +
	"\aScanLog\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12)\n" +
	"\x05level\x18\x04 \x01(\x0e2\x13.avscanner.LogLevelR\x05level\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\"W\n" +
	"\x0eAVCheckRequest\x12 \n" +
	"\fav_tool_name\x18\x01 \x01(\tR\n" +
	"avToolName\x12#\n" +
	"\rcheck_command\x18\x02 \x01(\tR\fcheckCommand\"s\n" +
	"\x0fAVCheckResponse\x12!\n" +
	"\fis_installed\x18\x01 \x01(\bR\visInstalled\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"T\n" +
	"\rAVInfoRequest\x12 \n" +
	"\fav_tool_name\x18\x01 \x01(\tR\n" +
	"avToolName\x12!\n" +
	"\finfo_command\x18\x02 \x01(\tR\vinfoCommand\"\x9d\x01\n" +
	"\x0eAVInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12+\n" +
	"\x11signature_version\x18\x02 \x01(\tR\x10signatureVersion\x12\x1f\n" +
	"\vlast_update\x18\x03 \x01(\tR\n" +
	"lastUpdate\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"9\n" +
	"\x12HealthCheckRequest\x12#\n" +
	"\rcheck_command\x18\x01 \x01(\tR\fcheckCommand\"\x83\x01\n" +
	"\x13HealthCheckResponse\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06issues\x18\x03 \x03(\tR\x06issues\x12\x1d\n" +
	"\n" +
	"last_check\x18\x04 \x01(\tR\tlastCheck\"\xb5\x01\n" +
	"\x10ResourceResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x01R\tdiskUsage\x12!\n" +
	"\factive_scans\x18\x04 \x01(\x05R\vactiveScans\x12\x1f\n" +
	"\vlast_update\x18\x05 \x01(\tR\n" +
	"lastUpdate\"m\n" +
	"\x15StreamResourceRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds*7\n" +
	"\bLogLevel\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\t\n" +
	"\x05DEBUG\x10\x032F\n" +
	"\tAVScanner\x129\n" +
	"\tStartScan\x12\x16.avscanner.ScanRequest\x1a\x12.avscanner.ScanLog0\x012\x97\x01\n" +
	"\bAVStatus\x12I\n" +
	"\x10CheckAVInstalled\x12\x19.avscanner.AVCheckRequest\x1a\x1a.avscanner.AVCheckResponse\x12@\n" +
	"\tGetAVInfo\x12\x18.avscanner.AVInfoRequest\x1a\x19.avscanner.AVInfoResponse2\xb7\x01\n" +
	"\tVMMonitor\x12R\n" +
	"\x11CheckServerHealth\x12\x1d.avscanner.HealthCheckRequest\x1a\x1e.avscanner.HealthCheckResponse\x12V\n" +
	"\x13StreamResourceUsage\x12 .avscanner.StreamResourceRequest\x1a\x1b.avscanner.ResourceResponse0\x01B0Z.gitlab.com/magnetite1/av-pipeline/server/protob\x06proto3"

var (
	file_av_scanner_proto_rawDescOnce sync.Once
	file_av_scanner_proto_rawDescData []byte
)

func file_av_scanner_proto_rawDescGZIP() []byte {
	file_av_scanner_proto_rawDescOnce.Do(func() {
		file_av_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_av_scanner_proto_rawDesc), len(file_av_scanner_proto_rawDesc)))
	})
	return file_av_scanner_proto_rawDescData
}

var file_av_scanner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_av_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_av_scanner_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: avscanner.LogLevel
	(*ScanRequest)(nil),           // 1: avscanner.ScanRequest
	(*ScanLog)(nil),               // 2: avscanner.ScanLog
	(*AVCheckRequest)(nil),        // 3: avscanner.AVCheckRequest
	(*AVCheckResponse)(nil),       // 4: avscanner.AVCheckResponse
	(*AVInfoRequest)(nil),         // 5: avscanner.AVInfoRequest
	(*AVInfoResponse)(nil),        // 6: avscanner.AVInfoResponse
	(*HealthCheckRequest)(nil),    // 7: avscanner.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 8: avscanner.HealthCheckResponse
	(*ResourceResponse)(nil),      // 9: avscanner.ResourceResponse
	(*StreamResourceRequest)(nil), // 10: avscanner.StreamResourceRequest
}
var file_av_scanner_proto_depIdxs = []int32{
	0,  // 0: avscanner.ScanLog.level:type_name -> avscanner.LogLevel
	1,  // 1: avscanner.AVScanner.StartScan:input_type -> avscanner.ScanRequest
	3,  // 2: avscanner.AVStatus.CheckAVInstalled:input_type -> avscanner.AVCheckRequest
	5,  // 3: avscanner.AVStatus.GetAVInfo:input_type -> avscanner.AVInfoRequest
	7,  // 4: avscanner.VMMonitor.CheckServerHealth:input_type -> avscanner.HealthCheckRequest
	10, // 5: avscanner.VMMonitor.StreamResourceUsage:input_type -> avscanner.StreamResourceRequest
	2,  // 6: avscanner.AVScanner.StartScan:output_type -> avscanner.ScanLog
	4,  // 7: avscanner.AVStatus.CheckAVInstalled:output_type -> avscanner.AVCheckResponse
	6,  // 8: avscanner.AVStatus.GetAVInfo:output_type -> avscanner.AVInfoResponse
	8,  // 9: avscanner.VMMonitor.CheckServerHealth:output_type -> avscanner.HealthCheckResponse
	9,  // 10: avscanner.VMMonitor.StreamResourceUsage:output_type -> avscanner.ResourceResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_av_scanner_proto_init() }
func file_av_scanner_proto_init() {
	if File_av_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_av_scanner_proto_rawDesc), len(file_av_scanner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_av_scanner_proto_goTypes,
		DependencyIndexes: file_av_scanner_proto_depIdxs,
		EnumInfos:         file_av_scanner_proto_enumTypes,
		MessageInfos:      file_av_scanner_proto_msgTypes,
	}.Build()
	File_av_scanner_proto = out.File
	file_av_scanner_proto_goTypes = nil
	file_av_scanner_proto_depIdxs = nil
}
